name: DDSeg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - nibabel
  - scikit-image
  - h5py
  - pytorch
  - torchvision
  - pip
  - pip:
      - onnxruntime
